export const ORDER_LIST_REQUEST = 'ORDER_LIST_REQUEST';
export const ORDER_LIST_SUCCESS = 'ORDER_LIST_SUCCESS';
export const ORDER_LIST_FAIL = 'ORDER_LIST_FAIL';

export const ADD__ORDER_LIST_REQUEST = 'ORDER_LIST_REQUEST';
export const ADD_ORDER_LIST_SUCCESS = 'ORDER_LIST_SUCCESS';
export const ADD_ORDER_LIST_FAIL = 'ORDER_LIST_FAIL';

export const EDIT__ORDER_LIST_REQUEST = 'ORDER_LIST_REQUEST';
export const EDIT_ORDER_LIST_SUCCESS = 'ORDER_LIST_SUCCESS';
export const EDIT_ORDER_LIST_FAIL = 'ORDER_LIST_FAIL';

export const DELETE__ORDER_LIST_REQUEST = 'ORDER_LIST_REQUEST';
export const DELETE_ORDER_LIST_SUCCESS = 'ORDER_LIST_SUCCESS';
export const DELETE_ORDER_LIST_FAIL = 'ORDER_LIST_FAIL';
