export const PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST';
export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS';
export const PRODUCT_LIST_FAIL = 'PRODUCT_LIST_FAIL';

export const ADD__PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST';
export const ADD_PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS';
export const ADD_PRODUCT_LIST_FAIL = 'PRODUCT_LIST_FAIL';

export const EDIT__PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST';
export const EDIT_PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS';
export const EDIT_PRODUCT_LIST_FAIL = 'PRODUCT_LIST_FAIL';

export const DELETE__PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST';
export const DELETE_PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS';
export const DELETE_PRODUCT_LIST_FAIL = 'PRODUCT_LIST_FAIL';
